# Generated by Django 4.1 on 2022-12-18 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_created=True)),
                ('availableSizes', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3)),
                ('currencyFormat', models.CharField(default='TND', max_length=3)),
                ('currencyId', models.CharField(default='TND', max_length=3)),
                ('description', models.TextField()),
                ('installments', models.IntegerField()),
                ('isFreeShipping', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
